name: CI - Build & Test Roleworld Engine

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies for Roleworld
        run: dotnet restore Roleworld/

      - name: Build Roleworld
        run: dotnet build Roleworld/ --configuration Release --no-restore

      - name: Run tests from Engine.Tests
        run: dotnet test Engine.Tests/ --no-build --verbosity normal
